name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      # Mise en cache des dépendances pour une meilleure performance
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Installation des dépendances avec gestion des erreurs
      - name: Install dependencies (with error handling)
        run: |
          npm install || (echo "Échec de l'installation des dépendances. Voir les journaux pour plus de détails." && exit 1)

      # Lancement du script dev avec gestion des erreurs
      - name: Run dev script (with error handling)
        run: |
          npm run dev || (echo "Erreur lors de l'exécution du script dev. Voir les journaux pour plus de détails." && exit 1)

      # (Optionnel) Ajout d'étapes de linting et de tests ici
